export type userProps = {
    _id: string
    userName: string,
    email: string,
    passWord: string,
    roles: string[],
    login: boolean,
    isVerified: boolean,
    verificationToken: string,
    verificationTokenExpiryData: number,
    forgetPassWordToken: string,
    forgetPassWordTokenExpiryData: number,
    avatar: string,
    dateOfBirth: string,
    displayDateOfBirth: boolean,
    displayEmails: string[],
    displayPhoneNumbers: string[],
    website: string,
    professions: string[],
    country: string,
    sex: string,
    bio: string,
    likes: string[],
};